/* This file was automatically generated by CasADi 3.7.2.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) xNext_generated_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int long long int
#endif

/* Add prefix to internal symbols */
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_f1 CASADI_PREFIX(f1)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

static const casadi_int casadi_s0[3] = {5, 1, 1};
static const casadi_int casadi_s1[3] = {3, 1, 1};

/* F:(x0[5],z0[5],p[3],u[0],adj_xf[],adj_zf[],adj_qf[])->(xf[5],zf[5],qf[0],adj_x0[],adj_z0[],adj_p[],adj_u[]) */
static int casadi_f1(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  #error Code generation not supported for IdasInterface
  return 0;
}

/* xNext:(i0[5],i1[3])->(o0[5]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real **res1=res+1, *w0=w+530, *w1=w+535, *w2=w+540, *w5=w+543;
  const casadi_real **arg1=arg+2;
  /* #0: @0 = input[0][0] */
  casadi_copy(arg[0], 5, w0);
  /* #1: @1 = zeros(5x1) */
  casadi_clear(w1, 5);
  /* #2: @2 = input[1][0] */
  casadi_copy(arg[1], 3, w2);
  /* #3: @3 = 0x1 */
  /* #4: @4 = 0x0 */
  /* #5: {@5, NULL, NULL, NULL, NULL, NULL, NULL} = F(@0, @1, @2, @3, @4, @4, @4) */
  arg1[0]=w0;
  arg1[1]=w1;
  arg1[2]=w2;
  arg1[3]=0;
  arg1[4]=0;
  arg1[5]=0;
  arg1[6]=0;
  res1[0]=w5;
  res1[1]=0;
  res1[2]=0;
  res1[3]=0;
  res1[4]=0;
  res1[5]=0;
  res1[6]=0;
  if (casadi_f1(arg1, res1, iw, w, 0)) return 1;
  /* #6: output[0][0] = @5 */
  casadi_copy(w5, 5, res[0]);
  return 0;
}

CASADI_SYMBOL_EXPORT int xNext(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int xNext_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int xNext_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void xNext_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int xNext_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void xNext_release(int mem) {
}

CASADI_SYMBOL_EXPORT void xNext_incref(void) {
}

CASADI_SYMBOL_EXPORT void xNext_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int xNext_n_in(void) { return 2;}

CASADI_SYMBOL_EXPORT casadi_int xNext_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real xNext_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* xNext_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* xNext_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* xNext_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* xNext_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int xNext_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 20;
  if (sz_res) *sz_res = 14;
  if (sz_iw) *sz_iw = 11;
  if (sz_w) *sz_w = 548;
  return 0;
}

CASADI_SYMBOL_EXPORT int xNext_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 20*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 14*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 11*sizeof(casadi_int);
  if (sz_w) *sz_w = 548*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
