function create_vehicle_video(X_history, U_history, car_params, Ts, video_filename)

% This script was generated by Google Gemini + great prompting!!

% --- 0. SET UP CONSTANTS AND INITIAL CONDITIONS ---
if nargin < 5
    video_filename = 'Vehicle_Simulation_Output.avi';
end

% Get geometry from car_params (assumed structure from previous discussion)
a = car_params.geometry.a; % Distance from CG to rear axle (e.g., 1.20)
b = car_params.geometry.b; % Distance from CG to front axle (e.g., 1.50)
L = a + b; % Wheelbase
T = car_params.geometry.t; % Track width (e.g., 1.60)
r_wheel = car_params.geometry.r_wheel; % Wheel radius (e.g., 0.32)

% Simulation time properties
N_sim = size(X_history, 2);
t_history = 0:Ts:(N_sim-1)*Ts;

% Indices for the state vector X = [Vx, Vy, r, omega_2, omega_3]
VX_IDX = 1;
VY_IDX = 2;
R_IDX = 3;

% Indices for the input vector U = [T_L, T_R, delta]
TL_IDX = 1; % Left Torque
TR_IDX = 2; % Right Torque
DELTA_IDX = 3; % Steering Angle

% -------------------------------------------------------------------------
% 6. SET YOUR SIMULATION DATA HERE
% Note: The script assumes X_history is a 5xN matrix and U_history is 3xN matrix
% where N is the number of time steps.
% -------------------------------------------------------------------------

% --- 1. & 3. INTEGRATE POSITION (Global X and Y) ---
% Integrate state vector to find global position (X, Y, Psi)
% Initial Global Position: (0, 0, 0)
X_pos = zeros(1, N_sim);
Y_pos = zeros(1, N_sim);
Psi_angle = zeros(1, N_sim);

% Simple Euler integration for global position and yaw angle
for k = 1:N_sim-1
    Vx = X_history(VX_IDX, k);
    Vy = X_history(VY_IDX, k);
    r = X_history(R_IDX, k);
    
    % Global velocity components
    V_global_x = Vx * cos(Psi_angle(k)) - Vy * sin(Psi_angle(k));
    V_global_y = Vx * sin(Psi_angle(k)) + Vy * cos(Psi_angle(k));
    
    % Update global position and yaw angle
    X_pos(k+1) = X_pos(k) + V_global_x * Ts;
    Y_pos(k+1) = Y_pos(k) + V_global_y * Ts;
    Psi_angle(k+1) = Psi_angle(k) + r * Ts;
end

% --- 2. SETUP PLOT, VIDEO WRITER, AND FRAME RATE ---
plot_rate_Hz = 400; % Output video frame rate
plot_skip = round(1 / (Ts * plot_rate_Hz));
if plot_skip < 1, plot_skip = 1; end
frame_indices = 1:plot_skip:N_sim;
video_fps = 120;  % changed from 30

v = VideoWriter(video_filename, 'Motion JPEG AVI');
v.FrameRate = video_fps;
open(v);

h_fig = figure('Position', [100, 100, 1200, 600], 'Color', 'w');
set(h_fig, 'MenuBar', 'none', 'ToolBar', 'none');

% Define the vehicle box corners in vehicle coordinates (CG is at [0,0])
car_verts_body = [
    b,  T/2;
    b, -T/2;
   -a, -T/2;
   -a,  T/2;
    b,  T/2 % Close the box
]';

% 4. SCALING: Define the view limits (Fixed Window)
% Since the vehicle speed is 10-50, we want the field of view to be dynamic in X,
% but fixed in Y to show lateral movement.
VIEW_WIDTH_Y = 6; % Fixed y-axis view distance (e.g., +/- 5m from center)
VIEW_LENGTH_X = 20; % Fixed x-axis view distance (e.g., 20m ahead)

% --- 5. LOOP THROUGH FRAMES ---
for k = frame_indices
    
    % Current vehicle state
    X_k = X_pos(k);
    Y_k = Y_pos(k);
    Psi_k = Psi_angle(k);
    
    % Vehicle Data Readout
    Vx = X_history(VX_IDX, k);
    Vy = X_history(VY_IDX, k);
    r = X_history(R_IDX, k);
    omega2 = X_history(4, k);
    omega3 = X_history(5, k);
    TL = U_history(TL_IDX, k);
    TR = U_history(TR_IDX, k);
    Delta = U_history(DELTA_IDX, k);
    
    % Clear and Set Axes for the next frame
    clf(h_fig);
    ax_map = axes('Parent', h_fig, 'Position', [0.05 0.1 0.65 0.8]); % Main Plot
    ax_data = axes('Parent', h_fig, 'Position', [0.75 0.1 0.20 0.8]); % Data Readout
    
    % --- TRANSFORM AND PLOT VEHICLE ---
    % Rotation Matrix (from global to body is not necessary here, use body to global)
    R_global = [cos(Psi_k), -sin(Psi_k);
                sin(Psi_k),  cos(Psi_k)];
    
    % Global vehicle coordinates
    car_verts_global = R_global * car_verts_body;
    car_verts_global(1,:) = car_verts_global(1,:) + X_k;
    car_verts_global(2,:) = car_verts_global(2,:) + Y_k;

    % Plot the vehicle box
    plot(ax_map, car_verts_global(1,:), car_verts_global(2,:), 'k-', 'LineWidth', 3);
    fill(ax_map, car_verts_global(1,:), car_verts_global(2,:), [0.8 0.8 0.8]);
    hold(ax_map, 'on');
    
    % Plot CG (red dot)
    plot(ax_map, X_k, Y_k, 'ro', 'MarkerFaceColor', 'r');

    % Plot heading vector (red arrow)
    quiver(ax_map, X_k, Y_k, R_global(1,1) * 0.5 * L, R_global(2,1) * 0.5 * L, 0, 'r', 'LineWidth', 2, 'MaxHeadSize', 5);

    % --- PLOT MOVING CENTERLINE (ROAD) ---
    % The centerline is fixed at Y=0 in a "road frame."
    % The centerline must be plotted over the view window for the current X_k.
    X_min_view = X_k - 0.1 * VIEW_LENGTH_X;
    X_max_view = X_k + 0.9 * VIEW_LENGTH_X;
    
    plot(ax_map, [X_min_view, X_max_view], [0, 0], 'k--', 'LineWidth', 1.5, 'DisplayName', 'Centerline');
    
    % --- AXES AND LABELS ---
    axis(ax_map, 'equal');
    xlim(ax_map, [X_k - 0.5*VIEW_LENGTH_X, X_k + 0.5*VIEW_LENGTH_X]); % Keep vehicle roughly centered in x-direction
    ylim(ax_map, [-VIEW_WIDTH_Y/2, VIEW_WIDTH_Y/2]); % Fixed Y-window for lane tracking
    
    title(ax_map, sprintf('Time: %.3f s (Frame %d)', t_history(k), k));
    xlabel(ax_map, 'Global X Position (m)');
    ylabel(ax_map, 'Global Y Position (m)');
    box(ax_map, 'on');

    % --- 5. DATA READOUT (Text) ---
    axis(ax_data, 'off'); % Turn off axes for clean text display
    text_y_start = 0.9;
    
    text(0.05, text_y_start, '--- Current Vehicle State (X) ---', 'FontWeight', 'bold', 'FontSize', 12, 'Parent', ax_data);
    text(0.05, text_y_start - 0.1, sprintf('V_x: %.2f m/s', Vx), 'Parent', ax_data);
    text(0.05, text_y_start - 0.15, sprintf('V_y: %.2f m/s', Vy), 'Parent', ax_data);
    text(0.05, text_y_start - 0.2, sprintf('Yaw Rate (r): %.2f deg/s', rad2deg(r)), 'Parent', ax_data);
    text(0.05, text_y_start - 0.25, sprintf('Wheel Speed L (w_2): %.1f rad/s', omega2), 'Parent', ax_data);
    text(0.05, text_y_start - 0.3, sprintf('Wheel Speed R (w_3): %.1f rad/s', omega3), 'Parent', ax_data);

    text(0.05, text_y_start - 0.45, '--- Current Control Input (U) ---', 'FontWeight', 'bold', 'FontSize', 12, 'Parent', ax_data);
    text(0.05, text_y_start - 0.55, sprintf('Torque Left (T_L): %.1f Nm', TL), 'Parent', ax_data);
    text(0.05, text_y_start - 0.6, sprintf('Torque Right (T_R): %.1f Nm', TR), 'Parent', ax_data);
    text(0.05, text_y_start - 0.65, sprintf('Steering (\delta): %.2f deg', rad2deg(Delta)), 'Parent', ax_data);
    
    % --- WRITE FRAME TO VIDEO ---
    frame = getframe(h_fig);
    writeVideo(v, frame);
end

% --- CLEAN UP ---
close(v);
close(h_fig);
disp(['Video saved successfully to: ', video_filename]);

end